export default [
  {
    img: "image 12.png",
    rating: 5.0,
    reviewCount: 6,
    country: "USA",
    title: "Life Lessons with Katie Zaferes",
    price: 136,
    status: "SOLD OUT",
  },
  {
    img: "wedding-photography 1.png",
    rating: 5.0,
    reviewCount: 30,
    country: "USA",
    title: "Learn wedding photography",
    price: 125,
    status: "ONLINE",
  },
  {
    img: "mountain-bike 1.png",
    rating: 4.8,
    reviewCount: 2,
    country: "USA",
    title: "Group Mountain Biking",
    price: 50,
    status: "OFFLINE",
  },
  {
    img: "image 12.png",
    rating: 4.5,
    reviewCount: 8,
    country: "Canada",
    title: "Adventure with Katie Zaferes",
    price: 150,
    status: "SOLD OUT",
  },
  {
    img: "wedding-photography 1.png",
    rating: 4.9,
    reviewCount: 25,
    country: "UK",
    title: "Mastering wedding photography",
    price: 110,
    status: "ONLINE",
  },
  {
    img: "mountain-bike 1.png",
    rating: 4.7,
    reviewCount: 5,
    country: "USA",
    title: "Solo Mountain Biking",
    price: 70,
    status: "SOLD OUT",
  },
  {
    img: "image 12.png",
    rating: 4.2,
    reviewCount: 10,
    country: "Australia",
    title: "Katie Zaferes' Insights",
    price: 120,
    status: "SOLD OUT",
  },
]
